# default configuration file for a masterless Windows minion.
# written to the minion during: "vagrant up" or "vagrant provision"
#
master: localhost
file_client: local  # do not try to contact a master
use_superseded:  # feature flags
  - module.run
file_roots:
  base:
    - c:/srv/salt  # user can define local Salt states here
    - c:/vagrant/salt_build_kit/salt
pillar_roots:
  base:
    - c:/srv/pillar  # user con define local settings here
    - c:/vagrant/salt_build_kit/pillar
file_ignore_regex:
  - '/\.git($|/)'
